USE db_lojagames;

INSERT INTO tb_categoria (nome_categoria, descricao, ativo) VALUES ("E-Sports", "Esporte eletrônico, ciberesporte ou esports, são alguns termos usados para as competições de jogos eletrônicos de forma profissional", true);
INSERT INTO tb_categoria (nome_categoria, descricao, ativo) VALUES ("Ação","Um jogo eletrônico de ação é um tipo de jogo eletrônico que desafia a velocidade, reflexo e raciocínio rápido do jogador. Jogos de ação geralmente incluem conflitos estratégicos, desafios de exploração e necessidade de solucionar quebra-cabeças simples", true);
INSERT INTO tb_categoria (nome_categoria, descricao, ativo) VALUES ("Aventura","Jogos de aventura, também conhecidos como adventures, são jogos eletrônicos cuja ênfase é focada no enredo e não na parte gráfica ou na ação. São caracterizados pela exploração dos cenários, pelos enigmas e quebra-cabeças (os chamados puzzles), pela interação com outros personagens e pelo foco na narrativa.", true);
INSERT INTO tb_categoria (nome_categoria, descricao, ativo) VALUES ("Estratégia","Jogo de estratégia é uma categoria de jogos (sejam de tabuleiro, de cartas, de videogames ou de computador) em que a habilidade dos jogadores em tomar decisões estratégicas supera a sorte como factor de determinação do jogador vencedor.", true);
INSERT INTO tb_categoria (nome_categoria, descricao, ativo) VALUES ("RPG","RPG é a sigla em inglês para role-playing game, um gênero de jogo no qual os jogadores assumem o papel de personagens imaginários, em um mundo fictício. Os jogos de RPG podem ser jogados de diversas formas, incluindo por um tabuleiro e videogame, ou PC.", true);
INSERT INTO tb_categoria (nome_categoria, descricao, ativo) VALUES ("Simulação","Jogos de simulação permitem que o jogador se insira dentro do ambiente sugerido pelo software ou site da internet. ... O jogador pode tanto administrar uma situação já existente, como criar e gerenciar sua criação e possíveis problemas derivados dela.", false);
INSERT INTO tb_categoria (nome_categoria, descricao, ativo) VALUES ("Outros","Jogos de tabuleiro em geral", true);

select * from tb_categoria;

INSERT INTO tb_produto (console, nome, descricao, quantidade, preco, categoria_id, foto) VALUES ("PS5", "Kena: Bridge of Spirits", "Kena: Bridge of Spirits é o projeto de estreia da Ember Lab e impressiona ainda mais a cada replay do trailer. O estilo único de arte mistura elementos marcantes da Pixar e do Studio Ghibli, resultando em uma incrível animação. O game também tem a aventura estampada em seu cartão de visitas e promete boas doses de puzzles em meio a grandes florestas encantadas.", 50, 500.00, 3, "https://i.imgur.com/YqasKzX.jpg");
INSERT INTO tb_produto (console, nome, descricao, quantidade, preco, categoria_id, foto) VALUES ("PS5", "Returnal", "um shooter com uma pegada um pouco diferente do habitual. A visão da câmera um pouco mais próxima da protagonista promete uma experiência singular com narrativa assustadora", 10, 400.00, 6, "https://i.imgur.com/Xd9vF7t.jpg");
INSERT INTO tb_produto (console, nome, descricao, quantidade, preco, categoria_id, foto) VALUES ("PS5", "Resident Evil Village", "Novo game da franquia de zumbis da Capcom e promete dar uma continuação majestosa ao legado do survival horror. Mais uma vez estaremos no controle de Ethan Winters e devemos escapar com vida de um misterioso vilarejo do interior europeu.", 20, 800.00, 3, "https://i.imgur.com/iQMTaVC.jpg");
INSERT INTO tb_produto (console, nome, descricao, quantidade, preco, categoria_id, foto) VALUES ("PS5", "God of War Ragnarok", "God of War Ragnarok promete dar continuidade à história de Kratos e Atreus. O Deus da Guerra se encaixou muito bem nos moldes da mitologia nórdica e conquistou até o GoTY em 2018 — em disputa acirrada contra Red Dead Redemption 2.", 100,  700.00, 3, "https://i.imgur.com/8qnAKwO.jpg");
INSERT INTO tb_produto (console, nome, descricao, quantidade, preco, categoria_id, foto) VALUES ("XBOX", "Halo Infinite", "O jogo colocará os jogadores de volta na sagrada armadura espartana de Master Chief, enquanto ele combate os Banidos, uma nova ameaça à humanidade, e promete mais liberdade do que qualquer jogo recente da série, com níveis enormes.", 80, 1000.00, 3, "https://i.imgur.com/ZnDckc2.jpg");
INSERT INTO tb_produto (console, nome, descricao, quantidade, preco, categoria_id, foto) VALUES ("XBOX", "Flight Simulator", "O Flight Simulator promete aos jogadores a liberdade de criar seus próprios planos de vôo e decolar em qualquer lugar do mundo, voando dia e noite em condições climáticas realistas.", 15, 250.00, 6, "https://i.imgur.com/cYl5vhh.jpg");

select * from tb_produto;